name: lunar_pitch
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0-232.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.2.2
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/x.png
    - assets/logo/google.png
    - assets/logo/lunar_pitch.png